import pagerank as pr
import random
def help():
    #pr.main('Desktop/School/hvd/pagerank/corpus0', 'Desktop/School/hvd/pagerank/corpus1' )
    crawl = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus0')
    crawl1 = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus1')
    crawl2 = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus2')


    transition = pr.transition_model(crawl, pr.randomItem(crawl), pr.DAMPING)
    transition1 =  pr.transition_model(crawl1, pr.randomItem(crawl1), pr.DAMPING)
    transition2 =  pr.transition_model(crawl2, pr.randomItem(crawl2), pr.DAMPING)
    print(transition)
    print('-')
    print(crawl)
    print('======')
    print(transition1)
    print(crawl1)
    print('-')
    print('======')
    print(transition2)
    print(crawl2)
    print('-')
#help()

def help1():
    crawl = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus0')
    crawl1 = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus1')
    crawl2 = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus2')
    print('===== c ===')
    print(crawl)
    print('-')
    print(pr.sample_pagerank(crawl, pr.DAMPING, pr.SAMPLES))
    print(' ')
    print('==== c1 ===')
    print(crawl1)
    print('-')
    print(pr.sample_pagerank(crawl1, pr.DAMPING, pr.SAMPLES))
    print(' ')
    print('===== c2 ====')
    print(crawl2)
    print('-')
    print(pr.sample_pagerank(crawl2, pr.DAMPING, pr.SAMPLES))
#help1()

def help2():
    crawl = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus0')
    crawl1 = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus1')
    crawl2 = pr.crawl('/Users/jevon/Desktop/School/hvd/pagerank/corpus2')
    print('===== c ===')
    print(crawl)
    print('-')
    print(pr.iterate_pagerank(crawl, pr.DAMPING))
    print(' ')
    print('==== c1 ===')
    print(crawl1)
    print('-')
    print(pr.iterate_pagerank(crawl1, pr.DAMPING))
    print(' ')
    print('===== c2 ====')
    print(crawl2)
    print('-')
    print(pr.iterate_pagerank(crawl2, pr.DAMPING))
help2()
